### ISSUE TITLE
Dependencies not compiling

### ISSUE THREAD

**Issue by drewboardman** [scalafx/scalafx-hello-world#6]
I'm getting the following errors

```
sbt:ScalaFX Hello World> run
[info] Updating {file:/home/drew/tmp/scalafx-hello-world/}scalafx-hello-world...
[info] Done updating.
[info] Compiling 1 Scala source to /home/drew/tmp/scalafx-hello-world/target/scala-2.12/classes ...
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.4. Compiling...
[info]   Compilation completed in 10.344s.
[error] /home/drew/tmp/scalafx-hello-world/src/main/scala/hello/ScalaFXHelloWorld.scala:42:3: Symbol 'type javafx.event.EventTarget' is missing from the classpath.
[error] This symbol is required by 'class scalafx.stage.Window'.
[error] Make sure that type EventTarget is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Window.class' was compiled against an incompatible version of javafx.event.
[error]   stage = new PrimaryStage {
[error]   ^
[error] /home/drew/tmp/scalafx-hello-world/src/main/scala/hello/ScalaFXHelloWorld.scala:45:17: Symbol 'term javafx.css' is missing from the classpath.
[error] This symbol is required by 'trait scalafx.css.Styleable'.
[error] Make sure that term css is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Styleable.class' was compiled against an incompatible version of javafx.
[error]     scene = new Scene {
[error]                 ^
[error] /home/drew/tmp/scalafx-hello-world/src/main/scala/hello/ScalaFXHelloWorld.scala:45:5: Symbol 'type javafx.scene.Scene' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.Scene'.
[error] Make sure that type Scene is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Scene.class' was compiled against an incompatible version of javafx.scene.
[error]     scene = new Scene {
[error]     ^
[error] /home/drew/tmp/scalafx-hello-world/src/main/scala/hello/ScalaFXHelloWorld.scala:50:15: Symbol 'type javafx.scene.text.Text' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.text.Text'.
[error] Make sure that type Text is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Text.class' was compiled against an incompatible version of javafx.scene.text.
[error]           new Text {
[error]               ^
[error] /home/drew/tmp/scalafx-hello-world/src/main/scala/hello/ScalaFXHelloWorld.scala:53:24: Symbol 'term javafx.scene.paint' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.paint.LinearGradient'.
[error] Make sure that term paint is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'LinearGradient.class' was compiled against an incompatible version of javafx.scene.
[error]             fill = new LinearGradient(
[error]                        ^
[error] /home/drew/tmp/scalafx-hello-world/src/main/scala/hello/ScalaFXHelloWorld.scala:64:26: Symbol 'type javafx.scene.effect.DropShadow' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.effect.DropShadow'.
[error] Make sure that type DropShadow is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'DropShadow.class' was compiled against an incompatible version of javafx.scene.effect.
[error]             effect = new DropShadow {
[error]                          ^
[error] 6 errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 11 s, completed Nov 12, 2017 10:50:36 AM
sbt:ScalaFX Hello World> 
```

**Comment by jpsacha** [comment]
Which version of OS and which version of Java are you using?

**Comment by ppopoff** [comment]
Have the same issue:
```
Fedora 25:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by JakeEP** [comment]
On Ubuntu, installing the following packages fixed it for me:

libopenjfx-java
openjfx

**Comment by jpsacha** [comment]
When using OpenJDK you need to also install JavaFX to avoid missing symbol errors. as described by @JakeEP.

**Comment by jerome-diver** [comment]
same problem here from archlinux and scala-2.13.0 installed. After install java-openjfx it doesn't fix the problem.

error:
[info] Loading project definition from /home/jerome/PROGRAMATION/Scala/helloWorld/project
[info] Loading settings for project helloworld from build.sbt ...
[info] Set current project to helloworld (in build file:/home/jerome/PROGRAMATION/Scala/helloWorld/)
[info] Compiling 1 Scala source to /home/jerome/PROGRAMATION/Scala/helloWorld/target/scala-2.12/classes ...
[error] /home/jerome/PROGRAMATION/Scala/helloWorld/hello.scala:15:3: Symbol 'type javafx.event.EventTarget' is missing from the classpath.
[error] This symbol is required by 'class scalafx.stage.Window'.
[error] Make sure that type EventTarget is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Window.class' was compiled against an incompatible version of javafx.event.
[error]   stage = new PrimaryStage {
[error]   ^
[error] /home/jerome/PROGRAMATION/Scala/helloWorld/hello.scala:17:17: Symbol 'term javafx.css' is missing from the classpath.
[error] This symbol is required by 'trait scalafx.css.Styleable'.
[error] Make sure that term css is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Styleable.class' was compiled against an incompatible version of javafx.
[error]     scene = new Scene {
[error]                 ^
[error] /home/jerome/PROGRAMATION/Scala/helloWorld/hello.scala:17:5: Symbol 'type javafx.scene.Scene' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.Scene'.
[error] Make sure that type Scene is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Scene.class' was compiled against an incompatible version of javafx.scene.
[error]     scene = new Scene {
[error]     ^
[error] /home/jerome/PROGRAMATION/Scala/helloWorld/hello.scala:22:15: Symbol 'type javafx.scene.text.Text' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.text.Text'.
[error] Make sure that type Text is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Text.class' was compiled against an incompatible version of javafx.scene.text.
[error]           new Text {
[error]               ^
[error] /home/jerome/PROGRAMATION/Scala/helloWorld/hello.scala:25:24: Symbol 'term javafx.scene.paint' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.paint.LinearGradient'.
[error] Make sure that term paint is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'LinearGradient.class' was compiled against an incompatible version of javafx.scene.
[error]             fill = new LinearGradient(
[error]                        ^
[error] /home/jerome/PROGRAMATION/Scala/helloWorld/hello.scala:36:26: Symbol 'type javafx.scene.effect.DropShadow' is missing from the classpath.
[error] This symbol is required by 'class scalafx.scene.effect.DropShadow'.
[error] Make sure that type DropShadow is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'DropShadow.class' was compiled against an incompatible version of javafx.scene.effect.
[error]             effect = new DropShadow {
[error]                          ^
[error] 6 errors found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed 13 juil. 2019 à 19:26:07

Solution was on archlinux to swap java version used (because i was under java-12):
```bash
sudo archlinux-java set java-8-openjdk
```

**Comment by jpsacha** [comment]
Update SBT setup (javafx is a dependency) and updated README (use java 11 or newer) should resolve this issue
