### ISSUE TITLE
Error:scalac: No 'scala-library*.jar' in Scala compiler classpath in Scala SDK 

### ISSUE THREAD

**Issue by AlanKassis** [scalafx/scalafx-hello-world#7]
I'm using Java 8
I have Scala 2.12.4
using Scalafx 8.0.144-R12
using IntelliJ 2017.3 
sbt version 1.0.2

I'm getting error:
Error:scalac: No 'scala-library*.jar' in Scala compiler classpath in Scala SDK sbt: org.scala-lang:scala-library:2.12.4:jar
when I try to debug the scalafx-hello-world example 

I can run it from the sbt shell and the UI will display 

here's what my build.sbt looks like 

![image](https://user-images.githubusercontent.com/5070429/37594968-ae8fe284-2bc2-11e8-81e0-bcd50fd4235e.png)

**Comment by jpsacha** [comment]
Are you using OpenJDK?

On Mar 19, 2018 8:15 AM, "Saleam" <notifications@github.com> wrote:

I'm using Java 8
I have Scala 2.12.4
using Scalafx 8.0.144-R12
using IntelliJ 2017.3
sbt version 1.0.2

I'm getting error:
Error:scalac: No 'scala-library*.jar' in Scala compiler classpath in Scala
SDK sbt: org.scala-lang:scala-library:2.12.4:jar
when I try to debug the scalafx-hello-world example

I can run it from the sbt shell and the UI will display

here's what my build.sbt looks like

[image: image]
<https://user-images.githubusercontent.com/5070429/37594968-ae8fe284-2bc2-11e8-81e0-bcd50fd4235e.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scalafx/scalafx-hello-world/issues/7>, or mute the
thread

**Comment by AlanKassis** [comment]
![image](https://user-images.githubusercontent.com/5070429/37655532-5b754434-2c91-11e8-9acb-1d23978c1c2b.png)
I'm not using OpenJDK 
I managed to fix the problem by creating a new project and importing the SBT through Intellij Idea and copy-pasting the code rather than opening straight from Git.

**Comment by jpsacha** [comment]
README states to use Java 11 or newer
